### ISSUE TITLE
Setting boss name is confusing

### ISSUE THREAD

**Issue by skerit** [Browsit/BossQuestsModule#1]
-I made a custom boss called "Angry Bucker", and it's part of a quest stage. But when I actually kill them, the objective is still stuck on 0 kills.-

I initially named my boss "angry_bucker", but then renamed it to "Angry Bucker", however it still was called "angry_bucker" internally in Boss.

The quests editor is a bit confusing, in that it works with full names instead of internal names. So when I entered "Angry Bucker" I expected it to work, but it didn't. Even though it did not throw an error, like "Boss not found" when editing the quest.

Once I used the internal boss name, it started working.

**Comment by PikaMug** [comment]
Thanks for your suggestion. I feel as though this is more of an issue with Boss, as the plugin no longer exposes the original name if a custom name has been set, despite continuing to use it internally. Still, I can see this being enough of an issue for a workaround.

I'll push a fix for this shortly, however I won't be releasing a build until https://github.com/PikaMug/BossQuestsModule/issues/2 has been resolved. Feel free to compile the module yourself if you need it before then.
