### ISSUE TITLE
No longer working with Boss 4.0+

### ISSUE THREAD

**Issue by SoraShiunin** [Browsit/BossQuestsModule#3]
Hello. (And Happy Holidays)
Boss had an overhaul and the module doesn't seem to work anymore. I get this error upon killing a boss previously defined in a quest.
https://pastebin.com/9PyVZvU
Also its a bit weird with questsGUI but I guess thats because its broken; Upon typing boss name, it just returns to the boss module, so the only thing you can do is click the menu to type the boss name again. Have to type cancel to exit.

Quests version 4.1.2-b283
Boss 4.1.4

**Comment by PikaMug** [comment]
Thanks for the report. Please share your pastebin again; it expired.

**Comment by SoraShiunin** [comment]
https://pastebin.com/KVy1GyBY
Here it is. Strange it was set to never expire, I guess someone deleted it.

**Comment by PikaMug** [comment]
Waiting on https://github.com/kangarko/Boss/issues/971

**Comment by PikaMug** [comment]
Resolved in ab93894bc3f0c05bea6764b462cda0e4c54ad199
